spring.application.name=TeachMeSomethingProject

paypal.client.id=AXp76mR0Tu20Jt_jp9Vj1IwUcthO0hh24zZD0P6ZauC-xYLrkp5gqfFV9pb1IkbCdkIwKgOa4XgyBjVy
paypal.client.secret=ECe3M4At3S8AG1Mjc508UCGfya-OG9t13y6kG0_78QL2SJWrLImAPSRmyllf0Aiinl0xSJxGDyuBTP8
paypal.base.url=https://api-m.sandbox.paypal.com